name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
    - name: Generate key
      run: php artisan key:generate
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Start MySQL Service
      run: sudo service mysql start
    - name: Set MySQL Root Password
      run: sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'your_password'; FLUSH PRIVILEGES;"
    - name: Create Database
      run: sudo mysql -u root -pyour_password -e 'CREATE DATABASE IF NOT EXISTS test_db;'
    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: 'your_password'
      run: php artisan test

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
    - name: Build Project
      run: npm install && php artisan migrate
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
